jobs:
- ${{ each distro in parameters.distros }}:
    - ${{ each dotnetVersion in parameters.dotnetVersions }}:
      - job:
        displayName: 'Artifacts Test ${{ distro }} ${{ dotnetVersion }} (${{ parameters.name }})'
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
        - template: common-steps.yml
          parameters:
            includeArtifacts: true
        - pwsh: ./build.ps1 -target Artifacts-Test -DockerDistro ${{ distro }} -DockerDotnetVersion ${{ dotnetVersion }}
          displayName: '[Docker Test Artifacts ${{ distro }}_${{ dotnetVersion }}]'
